pipeline {
    agent any 
  
    tools{
        maven 'Maven 3.6.0'
        jdk 'java1.8.0'
    }
    stages {
        stage('Build') { 
            steps
          {
              sh "mvn -B -DskipTests clean package"
          }  
        }
  stage('Test') { 
            steps
          {
              sh "mvn test"
          } 
      post{
          always{
              junit 'target/surefire-reports/*.xml'
          }
      }
        }  
            stage('Deploy'){
              steps{
                    sh 'java -jar target/com.mycompany.app.App.jar'
              }
    }
}
}
