pipeline {
    agent any 
  
    tools{
        maven 'Maven 3.6.0'
        jdk 'java1.8.0'
    }
    stages {
        stage('Build') { 
            steps
          {
              sh "mvn -B -DskipTests clean package"
          }  
        }
  stage('Test') { 
            steps
          {
              sh "mvn test"
          } 
      post{
          always{
              junit 'target/surefire-reports/*.xml'
          }
      }
        }  
  
    stage('SonarQube analysis') {
        steps{
    withSonarQubeEnv('SonarQube')
        {
      // requires SonarQube Scanner for Maven 3.2+
      sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'    
        }
             }
    }
        
 /*      
         stage('clone'){
            steps{
                git branch: 'master',url:"https://github.com/suhitabhowal/simple-java-maven-app.git/"
            }
        }
    
        stage('Artifactory Configuration'){
            steps{
                rtServer(
                    id:"ARTIFACTORY_SERVER",
                    url:"http://54.201.149.191:8081/artifactory",
                    credentialsId:'Artifactory-ID'
                )
                rtMavenDeployer(
                    id:"MAVEN_DEPLOYER",
                    serverId:"ARTIFACTORY_SERVER",
                    releaseRepo:"libs-release-local",
                    snapshotRepo:"libs-snapshot-local"
                    )
               rtMavenResolver(
                    id:"MAVEN_RESOLVER",
                    serverId:"ARTIFACTORY_SERVER",
                    releaseRepo:"libs-release",
                    snapshotRepo:"libs-snapshot"
                    )
                
            }
        }
        
        stage('Exec Maven'){
            
            steps{
                rtMavenRun(
                    tool:"Maven 3.6.0",
                    pom:'pom.xml',
                    goals:'clean install',
                    deployerId:"MAVEN_DEPLOYER",
                    resolverId:'MAVEN_RESOLVER'
                    
                    )
                
            }
            
        }
        
        stage('Publish Build Info'){
              steps{
                  rtPublishBuildInfo(
                      serverId:"ARTIFACTORY_SERVER"
                      )
              }
        }
        stage('Deploy'){
              steps{
                    sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
                  //sh 'scp -o StrictHostKeyChecking=no -i /tmp/mypem.pem target/my-app-1.0-SNAPSHOT.jar centos@54.185.147.65:/tmp/'
                  //sh 'ssh -i /tmp/mypem.pem centos@54.185.147.65 java -jar /tmp/my-app-1.0-SNAPSHOT.jar'
              }
              
            }
 comment ends*/      
}

}

